### ISSUE TITLE
Windows 10: npm install fails on fresh clone

### ISSUE THREAD

**Issue by ahelwer** [salesforce/runway-browser#10]
66506 error Windows_NT 10.0.10586
66507 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
66508 error node v4.4.6
66509 error npm  v2.15.5
66510 error code ELIFECYCLE
66511 error runway-browser@0.1.0 postinstall: `npm ls --prod --json > dist/deps.json; npm run webpack`
66511 error Exit status 1
66512 error Failed at the runway-browser@0.1.0 postinstall script 'npm ls --prod --json > dist/deps.json; npm run webpack'.
66512 error This is most likely a problem with the runway-browser package,
66512 error not with npm itself.
66512 error Tell the author that this fails on your system:
66512 error     npm ls --prod --json > dist/deps.json; npm run webpack
66512 error You can get information on how to open an issue for this project with:
66512 error     npm bugs runway-browser
66512 error Or if that isn't available, you can get their info via:
66512 error
66512 error     npm owner ls runway-browser
66512 error There is likely additional logging output above.
66513 verbose exit [ 1, true ]
[npm-debug.txt](https://github.com/salesforce/runway-browser/files/333908/npm-debug.txt)

**Comment by ahelwer** [comment]
According to this StackOverflow question, you need to separate the commands with && instead of semicolon. I tried this and it worked. I'll submit a pull request.

**Comment by ongardie** [comment]
Missing link, @ahelwer? I don't have a Windows machine to test on, but that's fine by me.
