### ISSUE TITLE
JavaScript safety warning cannot be dismissed

### ISSUE THREAD

**Issue by heidi-ann** [salesforce/runway-browser#3]
**Details:**
After clicking continue on the JavaScript safety warning, the model is loaded into runway but the warning remains. Clicking cancel redirects to http://localhost:3030/? and re-clicking continue has no effect.

**Steps to reproduce:**
1.  run runway locally and visit http://localhost:3030/?model=github.com/heidi-ann/runway-model-randcounter or visit http://runway.systems/?model=github.com/heidi-ann/runway-model-randcounter
2.  click continue

**Tested on:** 
chrome browser running on OS X 10.10.5

<img width="1428" alt="screen shot 2016-05-23 at 18 44 02" src="https://cloud.githubusercontent.com/assets/1835251/15479455/2db7dd3a-2118-11e6-9cfa-9d03b042d717.png">

**Comment by ongardie-sfdc** [comment]
Oops, sorry @heidi-ann, I'll fix that now.

BTW, if you're starting a new model, I suggest using d3.js instead of React (see https://github.com/ongardie/runway-model-raft for an example). I'm hoping to remove the React dependency eventually.

**Comment by ongardie-sfdc** [comment]
I think that's now fixed and deployed to https://runway.systems/.

**Comment by heidi-ann** [comment]
@ongardie-sfdc thanks, it is now working as expected
