### ISSUE TITLE
google snippet for runway.systems is bad

### ISSUE THREAD

**Issue by ongardie** [salesforce/runway-browser#4]
It'd be better if this was less embarrassing (Some tooltip text!) and said something about what Runway is.

![google-runway systems](https://cloud.githubusercontent.com/assets/463856/15518130/297c30c0-21b0-11e6-93b6-6c0fb9b2b1b7.png)

**Comment by ongardie-sfdc** [comment]
Google's advice on that is here: https://support.google.com/webmasters/answer/35624?hl=en

**Comment by ongardie-sfdc** [comment]
better now with 3218b57
